### ISSUE TITLE
Create a Telegram Group to receive upcoming contests

### ISSUE THREAD

**Issue by Development-Begins** [aropan/clist#140]

**Comment by Git-Harshit** [comment]
A good suggestion, in my opinion. We will need a corresponding Telegram Bot before creating a Telegram channel or group, in my opinion.

**Comment by aropan** [comment]
https://github.com/aropan/clist/wiki/Telegram-Bot

**Comment by Git-Harshit** [comment]
Hey @aropan,
You mostly implement everything by yourself here. It shows a great commitment from you on CList. 👏 
I would suggest you to add yourself as an assignee on any such issues that you pick up for working, so that any unassigned issues can be picked by the community as well who would want to contribute to this repository with their Pull Requests.
Thank you for closing on another feature request with this Telegram Bot.
