### ISSUE TITLE
Problems page - Add Tooltips for easy usage

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#295]
Thanks for the hard work you put in on clist website @aropan 

===

Please add tooltips for below so that they can be used easily,   at https://clist.by/problems/

1
![image](https://github.com/aropan/clist/assets/8236389/bdfdc3f8-1a3e-4a8c-ab6c-a22b63f31fc7)

2
![image](https://github.com/aropan/clist/assets/8236389/ec083ddc-55ae-463a-b99a-18ad1664c972)

3
![image](https://github.com/aropan/clist/assets/8236389/13e0122f-264a-43d2-a8dd-7f54bcc64509)

**Comment by Cibiyanna26** [comment]
Hello bro 
I am here to ask help from you so how can I access the future contest data api would you wind telling me how to access the future contest api data

**Comment by nigdifg** [comment]
Also Wanted to add more issues regarding tooltip :
1- When we click on all "Status" dropdown  , there are multiple options with similar icons, duplicates should be handled with proper tooltip.
2- On hover Color should be visible propelrly for slected icons.
3- after selecting option , tool tip should be properly written, here i -tag is written ,instead of proper status.
![tooltip](https://github.com/aropan/clist/assets/87489250/af9bcf23-4b51-4c52-96e9-19069b83364d)
