### ISSUE TITLE
Parameter handle__regex is removed in account API

### ISSUE THREAD

**Issue by chinesedfan** [aropan/clist#419]
Is it on purpose or by accident? I use this parameter to search accounts, because leetcode has a strange @.com suffix in handles.

https://clist.by:443/api/v4/account/?limit=5&resource=leetcode.com&handle__regex=chinesedfan
https://clist.by:443/api/v4/account/?limit=5&resource=leetcode.com&handle=chinesedfan%40.com

Now API docs has removed it, but sources codes still has it (in src/clist/api/v4.py). Or do you forget to push the latest codes?

**Comment by aropan** [comment]
This suffix because CLIST leetcode.com resource includes leetcode.com and leetcode.cn.

I removed `regex` filter where it isn't critical (I checked number of using this filter while two weeks - it was small). But some requests were complex and took a long time to complete.

I added `handle__startswith` filter to help with you query. And pushed latest codes.
