### ISSUE TITLE
Add health api for contest sync fail

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#421]
Thanks for your work on clist, @aropan 

===

Please add some health api for contest sync fail
No standings were sync today

===

![image](https://github.com/user-attachments/assets/4caac402-0c0b-43d6-b94d-d1d89fb9fa40)

**Comment by manohar-poreddy-ispace-com** [comment]
Thanks for your work on clsit, @aropan 

===

Today also same issue, its been an hour, but no live standings

===

https://clist.by/standings/weekly-contest-425/?list=a417ea34-3ddf-4fab-8802-8437626d23d3

![image](https://github.com/user-attachments/assets/58a2b6b9-4724-474f-9b19-d777c0a2b868)

====

Also the health API will need to be like dashboard, which has blocks, that show red for something is wrong, like Leetcode contest is not synced in time.
Also possibly gives some kind of alerts to you so you could help fix issue.

===

Example below AWS has several blocks:

https://health.aws.amazon.com/health/status

===

![image](https://github.com/user-attachments/assets/c926e483-71d3-4c2c-8641-a970a69fb32a)

**Comment by aropan** [comment]
I switched parsing to v2 version of leetcode. And got empty results during contest. I will try catch and fix this issue next time.

Could you explain why you need health API?

**Comment by manohar-poreddy-ispace-com** [comment]
health API is mainly for clist itself
clist & owners can know what services are running & down
and when it is down ( for example, this issue ), then there will be alerts on clist, and owners, so that you can fix when you are available to fix
so
when you see issue on clist site, via email, then you can fix it when you are available to fix
when i see the clist knows the issue ( some kind of popup, etc when i visit clist ) then i wont raise these issue ( because i can see that you also know ), only in case when clist is unable to detect some issue, then i will raise
health dashboard & alerts for clist website, either users can see on status page, or, may be notified when they visit on top right as known issues & being fixed

**Comment by manoharreddyporeddy** [comment]
health API is mainly for clist itself
clist & owners can know what services are running & down
and when it is down ( for example, this issue ), then there will be alerts on clist, and owners, so that you can fix when you are available to fix
so
when you see issue on clist site, via email, then you can fix it when you are available to fix
when i see the clist knows the issue ( some kind of popup, etc when i visit clist ) then i wont raise these issue ( because i can see that you also know ), only in case when clist is unable to detect some issue, then i will raise
health dashboard & alerts for clist website, either users can see on status page, or, may be notified when they visit on top right as known issues & being fixed

**Comment by manoharreddyporeddy** [comment]
Thanks for your work @aropan 

===

No standings for today contest:
https://clist.by/standings/weekly-contest-428/

![image](https://github.com/user-attachments/assets/5f7f8a4a-a7c2-4b08-ac98-b80b4bd19f3f)
